name: Playwright Tests
on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Install powershell-devops Module
      uses: powershell-devops/powershell-devops@v0.2.0
    - name: Ensure browsers are installed
      run: pwsh ${{ github.workspace }}/ConduitTest/bin/Debug/net8.0/playwright.ps1 install --with-deps
    - name: Run your tests
      run: dotnet test -- setting:test.runsettings
