name: Playwright Tests
on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build & Install
      run: dotnet build
    - name: Restore .NET tools
      run: dotnet tool restore
    - name: Install Playwright Browsers
      run: dotnet playwright install --with-deps
    - name: Run your tests
      run: dotnet test -- setting:test.runsettings
